### ISSUE TITLE
Support silex 2

### ISSUE THREAD

**Issue by mvanbaak** [aws/aws-sdk-php-silex#13]
Since silex 2 has been released, it's time we support it ;-)

**Comment by cjyclaire** [comment]
Thanks for updating the PR! Yet due to #5, maybe backwards compatibility should also be considered? Any suggestions? @jeremeamia

**Comment by mvanbaak** [comment]
I think we should just handle it like all the other service providers.
Keep 2.0.2 for silex1, create a branch from master now called 2.0 and put the branch-alias for 2.0.x-dev in there, and have master become 3.0.0.

That way, because of semver, people will know 3.X is not compatible with 2.X. And if you state somewhere in the readme that for silex1 you need version ^2.0 of this provider, you are all set.

**Comment by jeremeamia** [comment]
@mvanbaak Yeah, I think that would be appropriate since the Silex 2 providers are not BC with Silex 1.

**Comment by cjyclaire** [comment]
Cool, make sense to me.

**Comment by mvanbaak** [comment]
Ok, I updated the readme.
Make sure that before this code is merged to master, you create a new branch 2.0 from master to be able to support bugfix versions to version 2 of this provider for silex 1 users.

Thanks.

**Comment by cjyclaire** [comment]
Credits to PR #12
