### ISSUE TITLE
Merge feature/support-silex-2 and tag version 3.0.0

### ISSUE THREAD

**Issue by mvanbaak** [aws/aws-sdk-php-silex#14]
Thanks a lot for merging the PR to support silex 2.

All that is left now is merge branch feature/support-silex-2 to master and tag version 3.0.0

Can you please do that?
I want to switch my composer.json to only use stable packages ;-)
Thanks a lot!

**Comment by cjyclaire** [comment]
Apology for delay on this, now is all set!
